name: CursedPlugin
version: '${project.version}'
main: me.muratcan.cursedplugin.CursedPlugin
api-version: 1.19
authors: [ MyEye ]
commands:
  iyileş:
    description: Oyuncunun canını yeniler.
    usage: /iyileş

  tanrı:
    description: kişiyi sadece ölümsüz yapar.
    usage: /tanrı

  görünmezlik:
    description: kişiyi görünmez yapar.
    usage: /görünmezlik

  beslen:
    description: açlığınızı doldurur.
    usage: /beslen

  evkaydet:
    description: olduğunuz konumu kaydedersiniz.
    usage: /evkaydet

  ev:
    description: kaydilen konuma geri ışınlar.
    usage: /ev

  geri:
    description: Sizi öldüğünüz konuma geri gönderir.
    usage: /geri

  esyaver:
    description: elinizde tutuğunuz bir eşyayı istediğiniz kişiye gönderir.
    usage: /esyaver <Oyuncu>

  ekipmanlar:
    description: Belli bir sürede bir birkaç eşya temin eder.
    usage: /ekipmanlar


  tamiret:
    description: elinizde tuttuğunuz ekipmanı tamir eder.
    usage: /tamiret

  uçma:
    description: oyuncunun uçmasını sağlar.
    usage: /uçma

  uçabilir:
    description: Yetkili kişi tarafından bir oyuncuya uçma yetkisi verir
    usage: /uçabilir <Oyuncu>

  yardım:
    description: Yardım menüsünü açar
    usage: /yardım

  spawnkaydet:
    description: global spawn noktasını belirler
    usage: /spawnkaydet


  başlangıç:
    description: global spawn noktasını gönderir
    usage: /başlangıç

  sakatla:
    description: özel eşya
    usage: /sakatla
  kan:
    description: özel başka eşya
    usage: /kan
  zehir:
    description: başka bir silah
    usage: /zehir
  kör:
    description: kör eden silah
    usage: /kör
